# -*- coding: utf-8 -*-
"""youtube downloader

Automatically generated by Colaboratory.

"""

# !pip install pytube

from pytube import YouTube
from sys import argv
from google.colab import files

def downloadvideo(link):
  # link = argv[1]
  # link = "https://www.youtube.com/watch?v=vEQ8CXFWLZU&ab_channel=InternetMadeCoder"
  yt = YouTube(link)
  print('**title :',yt.title, '** author :' ,yt.author, '** lenght : ', yt.length ,'** views :' ,yt.views , '**')
  yd = yt.streams.get_highest_resolution().download()
  files.download(yd)
  
downloadvideo('https://www.youtube.com/watch?v=2kx2aWfC09Q&ab_channel=ESPN')

ls -l

!rm *.mp4
